<?php
/**
 * Champs ACF pour les Services (Leistungen)
 *
 * Structure avec onglets similaire aux projets
 *
 * @package Socorif
 */

if (!defined('ABSPATH')) exit;

add_action('acf/include_fields', function() {
    if (!function_exists('acf_add_local_field_group')) return;

    acf_add_local_field_group([
        'key' => 'group_leistungen_details',
        'title' => 'Details du service',
        'fields' => [
            // 1. Onglet: Informations generales
            [
                'key' => 'field_leistung_tab_general',
                'label' => 'Informations',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_leistung_icon',
                'label' => 'Icone',
                'name' => 'leistung_icon',
                'type' => 'text',
                'instructions' => 'Classe Dashicons (ex: dashicons-hammer)',
                'wrapper' => ['width' => '50'],
                'default_value' => 'dashicons-admin-tools',
                'placeholder' => 'dashicons-admin-tools',
            ],
            [
                'key' => 'field_leistung_short_description',
                'label' => 'Description courte',
                'name' => 'short_description',
                'type' => 'textarea',
                'instructions' => 'Breve description pour les cartes et aperçus',
                'maxlength' => 200,
                'rows' => 3,
            ],
            [
                'key' => 'field_leistung_features',
                'label' => 'Points cles du service',
                'name' => 'service_features',
                'type' => 'repeater',
                'instructions' => 'Liste des avantages ou caracteristiques du service',
                'layout' => 'table',
                'button_label' => 'Ajouter un point',
                'min' => 0,
                'max' => 10,
                'sub_fields' => [
                    [
                        'key' => 'field_leistung_feature_text',
                        'label' => 'Texte',
                        'name' => 'text',
                        'type' => 'text',
                        'required' => 1,
                    ],
                ],
            ],

            // 2. Onglet: Processus
            [
                'key' => 'field_leistung_tab_process',
                'label' => 'Processus',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'field_leistung_process',
                'label' => 'Etapes du processus',
                'name' => 'service_process',
                'type' => 'repeater',
                'instructions' => 'Les etapes de realisation de ce service',
                'layout' => 'block',
                'button_label' => 'Ajouter une etape',
                'min' => 0,
                'max' => 10,
                'sub_fields' => [
                    [
                        'key' => 'field_leistung_process_title',
                        'label' => 'Etape',
                        'name' => 'title',
                        'type' => 'text',
                        'required' => 1,
                        'wrapper' => ['width' => '30'],
                    ],
                    [
                        'key' => 'field_leistung_process_description',
                        'label' => 'Description',
                        'name' => 'description',
                        'type' => 'textarea',
                        'rows' => 2,
                        'wrapper' => ['width' => '70'],
                    ],
                ],
            ],

            // 3. Onglet: FAQ / Accordeon
            [
                'key' => 'field_leistung_tab_faq',
                'label' => 'FAQ',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'field_leistung_faq_title',
                'label' => 'Titre de la section FAQ',
                'name' => 'service_faq_title',
                'type' => 'text',
                'default_value' => 'Questions frequentes',
            ],
            [
                'key' => 'field_leistung_faq',
                'label' => 'Questions / Reponses',
                'name' => 'service_faq',
                'type' => 'repeater',
                'instructions' => 'Ajoutez les questions frequentes sur ce service',
                'layout' => 'block',
                'button_label' => 'Ajouter une question',
                'min' => 0,
                'max' => 20,
                'sub_fields' => [
                    [
                        'key' => 'field_leistung_faq_question',
                        'label' => 'Question',
                        'name' => 'question',
                        'type' => 'text',
                        'required' => 1,
                    ],
                    [
                        'key' => 'field_leistung_faq_answer',
                        'label' => 'Reponse',
                        'name' => 'answer',
                        'type' => 'wysiwyg',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                    ],
                ],
            ],

            // 4. Onglet: Texte avec image
            [
                'key' => 'field_leistung_tab_text_image',
                'label' => 'Texte + Image',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'field_leistung_text_image_title',
                'label' => 'Titre de la section',
                'name' => 'service_text_image_title',
                'type' => 'text',
                'default_value' => 'Notre expertise',
            ],
            [
                'key' => 'field_leistung_text_image_content',
                'label' => 'Contenu',
                'name' => 'service_text_image_content',
                'type' => 'wysiwyg',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
            ],
            [
                'key' => 'field_leistung_text_image_image',
                'label' => 'Image',
                'name' => 'service_text_image_image',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_leistung_text_image_position',
                'label' => 'Position de l\'image',
                'name' => 'service_text_image_position',
                'type' => 'select',
                'choices' => ['left' => 'Gauche', 'right' => 'Droite'],
                'default_value' => 'right',
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_leistung_text_image_features',
                'label' => 'Points cles',
                'name' => 'service_text_image_features',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Ajouter un point',
                'min' => 0,
                'max' => 6,
                'sub_fields' => [
                    [
                        'key' => 'field_leistung_text_image_feature_text',
                        'label' => 'Texte',
                        'name' => 'text',
                        'type' => 'text',
                    ],
                ],
            ],

            // 5. Onglet: Medias
            [
                'key' => 'field_leistung_tab_medien',
                'label' => 'Medias',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'field_leistung_galerie',
                'label' => 'Galerie du service',
                'name' => 'service_galerie',
                'type' => 'gallery',
                'instructions' => 'Images illustrant ce service',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'insert' => 'append',
                'library' => 'all',
                'min' => 0,
                'max' => 20,
            ],
            [
                'key' => 'field_leistung_video_id',
                'label' => 'Video YouTube',
                'name' => 'service_video_id',
                'type' => 'text',
                'instructions' => 'Entrez l\'ID YouTube (ex: "dQw4w9WgXcQ") ou l\'URL complete',
                'placeholder' => 'dQw4w9WgXcQ ou https://www.youtube.com/watch?v=...',
            ],
            [
                'key' => 'field_leistung_vorher_bild',
                'label' => 'Image Avant',
                'name' => 'service_vorher_bild',
                'type' => 'image',
                'instructions' => 'Image avant intervention (optionnel)',
                'return_format' => 'array',
                'preview_size' => 'medium',
            ],
            [
                'key' => 'field_leistung_nachher_bild',
                'label' => 'Image Apres',
                'name' => 'service_nachher_bild',
                'type' => 'image',
                'instructions' => 'Image apres intervention (optionnel)',
                'return_format' => 'array',
                'preview_size' => 'medium',
            ],

            // 6. Onglet: Temoignages
            [
                'key' => 'field_leistung_tab_testimonial',
                'label' => 'Temoignages',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'field_leistung_testimonials_title',
                'label' => 'Titre de la section',
                'name' => 'service_testimonials_title',
                'type' => 'text',
                'default_value' => 'Ce que disent nos clients',
            ],
            [
                'key' => 'field_leistung_testimonials',
                'label' => 'Temoignages',
                'name' => 'service_testimonials',
                'type' => 'repeater',
                'instructions' => 'Ajoutez les temoignages de clients satisfaits',
                'layout' => 'block',
                'button_label' => 'Ajouter un temoignage',
                'min' => 0,
                'max' => 10,
                'sub_fields' => [
                    [
                        'key' => 'field_leistung_testimonial_quote',
                        'label' => 'Citation',
                        'name' => 'quote',
                        'type' => 'textarea',
                        'rows' => 3,
                        'required' => 1,
                    ],
                    [
                        'key' => 'field_leistung_testimonial_author',
                        'label' => 'Nom',
                        'name' => 'author',
                        'type' => 'text',
                        'wrapper' => ['width' => '33'],
                    ],
                    [
                        'key' => 'field_leistung_testimonial_position',
                        'label' => 'Fonction',
                        'name' => 'position',
                        'type' => 'text',
                        'wrapper' => ['width' => '33'],
                    ],
                    [
                        'key' => 'field_leistung_testimonial_image',
                        'label' => 'Photo',
                        'name' => 'image',
                        'type' => 'image',
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'wrapper' => ['width' => '33'],
                    ],
                ],
            ],

            // 7. Onglet: SEO
            [
                'key' => 'field_leistung_tab_seo',
                'label' => 'SEO',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'field_leistung_featured',
                'label' => 'Service mis en avant',
                'name' => 'service_featured',
                'type' => 'true_false',
                'instructions' => 'Mettre ce service en avant sur la page d\'accueil',
                'default_value' => 0,
                'ui' => 1,
            ],
            [
                'key' => 'field_leistung_order',
                'label' => 'Ordre d\'affichage',
                'name' => 'service_order',
                'type' => 'number',
                'instructions' => 'Ordre dans les listes (plus bas = plus haut)',
                'default_value' => 0,
                'min' => 0,
                'max' => 999,
            ],

            // 8. Onglet: Formulaire
            [
                'key' => 'field_leistung_tab_form',
                'label' => 'Formulaire',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'field_leistung_contact_form',
                'label' => 'Formulaire de contact',
                'name' => 'contact_form',
                'type' => 'post_object',
                'instructions' => 'Selectionnez le formulaire Contact Form 7 pour ce service.',
                'post_type' => ['wpcf7_contact_form'],
                'allow_null' => 1,
                'return_format' => 'id',
                'ui' => 1,
            ],

            // 9. Onglet: CTA
            [
                'key' => 'field_leistung_tab_cta',
                'label' => 'CTA',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'field_leistung_cta_subtitle',
                'label' => 'Sous-titre',
                'name' => 'service_cta_subtitle',
                'type' => 'text',
                'default_value' => 'Pret a demarrer?',
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_leistung_cta_title',
                'label' => 'Titre',
                'name' => 'service_cta_title',
                'type' => 'text',
                'default_value' => 'Demandez votre devis gratuit',
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_leistung_cta_description',
                'label' => 'Description',
                'name' => 'service_cta_description',
                'type' => 'textarea',
                'rows' => 2,
                'default_value' => 'Contactez-nous pour discuter de votre projet et obtenir une estimation personnalisee.',
            ],
            [
                'key' => 'field_leistung_cta_button_text',
                'label' => 'Texte du bouton',
                'name' => 'service_cta_button_text',
                'type' => 'text',
                'default_value' => 'Nous contacter',
                'wrapper' => ['width' => '50'],
            ],
            [
                'key' => 'field_leistung_cta_button_link',
                'label' => 'Lien du bouton',
                'name' => 'service_cta_button_link',
                'type' => 'link',
                'return_format' => 'array',
                'wrapper' => ['width' => '50'],
            ],

            // 10. Onglet: Banniere Pub
            [
                'key' => 'field_leistung_tab_banniere',
                'label' => 'Banniere Pub',
                'name' => '',
                'type' => 'tab',
                'placement' => 'top',
            ],
            [
                'key' => 'field_leistung_banniere_activer',
                'label' => 'Activer la banniere publicitaire',
                'name' => 'banniere_activer',
                'type' => 'true_false',
                'default_value' => 0,
                'ui' => 1,
            ],
            [
                'key' => 'field_leistung_banniere_subtitle',
                'label' => 'Sous-titre',
                'name' => 'banniere_subtitle',
                'type' => 'text',
                'default_value' => 'Expert en gestion de patrimoine internationale',
                'conditional_logic' => [[['field' => 'field_leistung_banniere_activer', 'operator' => '==', 'value' => '1']]],
            ],
            [
                'key' => 'field_leistung_banniere_title',
                'label' => 'Titre',
                'name' => 'banniere_title',
                'type' => 'textarea',
                'rows' => 2,
                'default_value' => 'VOUS AVEZ UN PROJET IMMOBILIER A L\'ETRANGER ?',
                'conditional_logic' => [[['field' => 'field_leistung_banniere_activer', 'operator' => '==', 'value' => '1']]],
            ],
            [
                'key' => 'field_leistung_banniere_image',
                'label' => 'Image',
                'name' => 'banniere_image',
                'type' => 'image',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'conditional_logic' => [[['field' => 'field_leistung_banniere_activer', 'operator' => '==', 'value' => '1']]],
            ],
            [
                'key' => 'field_leistung_banniere_button',
                'label' => 'Bouton',
                'name' => 'banniere_button',
                'type' => 'link',
                'return_format' => 'array',
                'conditional_logic' => [[['field' => 'field_leistung_banniere_activer', 'operator' => '==', 'value' => '1']]],
            ],
            [
                'key' => 'field_leistung_banniere_bg_color',
                'label' => 'Couleur de fond',
                'name' => 'banniere_bg_color',
                'type' => 'select',
                'choices' => ['primary' => 'Orange', 'secondary' => 'Bleu', 'dark' => 'Sombre'],
                'default_value' => 'secondary',
                'conditional_logic' => [[['field' => 'field_leistung_banniere_activer', 'operator' => '==', 'value' => '1']]],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'leistungen',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'active' => true,
    ]);
});
